name = "famcsskedtgbot"
main = "worker.js"
compatibility_date = "2026-08-30"

[vars]
API_BASE_URL = "https://famcsschedulebot.yarashsei.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "schedule_db"
database_id = "f3602b67-4b28-49f5-90a9-88745a580fd1"

[[queues.consumers]]
queue = "schedule-notifications"
max_batch_size = 5
max_batch_timeout = 5
max_retries = 5


[observability]
enabled = true
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
