name = "famcsskedtgbot"
main = "worker.js"
compatibility_date = "2026-08-30"


[observability]
enabled = true
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true